server:
  port: 9001
  servlet:
    context-path: /

spring:
  security:
    saml2:
      relyingparty:
        registration:
          sosec-beispiel:
            signing:
              credentials:
                - private-key-location: "classpath:credentials/private.key"
                  certificate-location: "classpath:credentials/public.crt"
            identityprovider:
              metadata-uri: http://idp:8080/something/saml/descriptor
              entity-id: http://idp:8080/something
